# font_family 3270 Nerd Font Mono
# font_family 3270 Nerd Font Mono
# font_family MesloLGLDZ Nerd Font Mono
# Fonts
font_family                     JetBrainsMonoNL-SemiBoldItalic
bold_font                       JetBrainsMono Nerd Font Mono ExtraBold
italic_font                     JetBrainsMono Nerd Font Mono Italic
bold_italic_font                JetBrainsMono Nerd Font Mono ExtraBold Italic
 
font_size 16
modify_font                     underline_position 150%
modify_font                     underline_thickness 1.05
modify_font                     cell_height 110%

## background
background_image ./kamado-tanjiro.png
# background #1c2e4a
# background_blur 50
background_opacity 1 
background_image_layout cscaled


## mouse
opy_on_select                  yes

background_tint 0.96
editor /opt/homebrew/bin/nvim

# tabbar
# tab_bar_edge    top
# tab_bar_margin_width    10
# tab_bar_margin_height    15 0
# tab_bar_style    fade
# tab_fade    0 
# tab_title_template          "{fmt.bg._080808}{fmt.fg._303030}{fmt.fg.default}{fmt.bg._303030}{fmt.fg._c6c6c6} {title} {fmt.fg.default}{fmt.bg.default}{fmt.fg._303030}{fmt.fg.default}"
# active_tab_title_template   "{fmt.bg._080808}{fmt.fg._80a0ff}{fmt.fg.default}{fmt.bg._80a0ff}{fmt.fg._080808} {title} {fmt.fg.default}{fmt.bg.default}{fmt.fg._80a0ff}{fmt.fg.default}"
tab_bar_style custom
tab_separator                   ""
# REF: https://github.com/kovidgoyal/kitty/discussions/4447
tab_fade                        0 0 0 0
tab_title_template              "{fmt.fg._415c6d}{fmt.bg.default}  {index}:{f'{title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 25 else title}{' []' if layout_name == 'stack' else ''} "
active_tab_title_template       "{fmt.fg._83b6af}{fmt.bg.default}  {index}:{f'{title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 25 else title}{' []' if layout_name == 'stack' else ''} "
tab_bar_edge                    top
tab_bar_align                   left
tab_bar_margin_width            0.0
tab_bar_margin_height           10.0 0.0
active_tab_font_style           bold-italic
inactive_tab_font_style         normal
tab_bar_min_tabs                2
tab_activity_symbol             none
bell_on_tab                     no
# or "🔔 "
#}}}

