# layouts
enabled_layouts splits, stack 

# Fonts
# font_family                     JetBrainsMonoNL-SemiBoldItalic
font_family                     JetBrainsMonoNL-Light
bold_font                       JetBrainsMono Nerd Font Mono ExtraBold
italic_font                     JetBrainsMono Nerd Font Mono Italic
bold_italic_font                JetBrainsMono Nerd Font Mono ExtraBold Italic
 
font_size 16
modify_font                     underline_position 150%
modify_font                     underline_thickness 1.05
modify_font                     cell_height 110%

## background
background_image ./kamado-tanjiro.png
background_opacity 1 
background_image_layout cscaled


## mouse
copy_on_select                  yes

background_tint 0.97
editor /opt/homebrew/bin/nvim

# tab bar styles
tab_bar_style custom
tab_separator                   ""
# REF: https://github.com/kovidgoyal/kitty/discussions/4447
tab_fade                        0 0 0 0
tab_title_template              "{fmt.fg._415c6d}{fmt.bg.default}  {index}:{f'{title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 25 else title}{' []' if layout_name == 'stack' else ''} "
active_tab_title_template       "{fmt.fg._83b6af}{fmt.bg.default}  {index}:{f'{title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 25 else title}{' []' if layout_name == 'stack' else ''} "
tab_bar_edge                    top
tab_bar_align                   left
tab_bar_margin_width            0.0
tab_bar_margin_height           10.0 0.0
active_tab_font_style           bold-italic
inactive_tab_font_style         normal
tab_bar_min_tabs                2
tab_activity_symbol             none
bell_on_tab                     no
# or "🔔 "
#}}}

# Tabs naviagation
map kitty_mod+[ next_tab
map kitty_mod+] previous_tab
map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 6
map kitty_mod+6 goto_tab 7
map kitty_mod+7 goto_tab 8
map kitty_mod+8 goto_tab 9
map kitty_mod+9 goto_tab 10

#open kitty config
map f12 launch --type=tab --hold --title=kitty-config nvim ~/.config/kitty/kitty.conf

# window styles
active_border_color #5a140b
inactive_border_color #360d08
single_window_padding_width 1 
window_padding_width 20
window_margin_width 0
window_border_width 1pt

# open lazygit
map f1 launch --cwd=current --type=overlay lazygit

# window splitting
map ctrl+" launch --cwd=current --location=hsplit
map ctrl+' launch --cwd=current --location=vsplit

# navigation hotkeys

map kitty_mod+z kitten zoom.py
# map kitty_mod+x goto_layout tall

#window navigation
map kitty_mod+h neighboring_window left
map kitty_mod+l neighboring_window right
map kitty_mod+k neighboring_window top
map kitty_mod+j neighboring_window bottom

map ctrl+shift+up layout_action move_to_screen_edge top
map ctrl+shift+left layout_action move_to_screen_edge left
map ctrl+shift+right layout_action move_to_screen_edge right
map ctrl+shift+down layout_action move_to_screen_edge bottom

