return {
	-- "nvim-neo-tree/neo-tree.nvim",
	-- branch = "v3.x",
	-- dependencies = {
	-- 	"nvim-lua/plenary.nvim",
	-- 	"nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
	-- 	"MunifTanjim/nui.nvim",
	-- },
	-- config = function()
	-- 	vim.keymap.set("n", "<leader>ef", ":Neotree filesystem reveal current<CR>", {})
	-- 	vim.keymap.set("n", "<leader>ee", ":Neotree filesystem reveal left<CR>", {})
	-- 	vim.keymap.set("n", "<leader>ec", ":Neotree close<CR>", {})
	--
	-- 	local function on_move(data)
	-- 		Snacks.rename.on_rename_file(data.source, data.destination)
	-- 	end
	--
	-- 	require("neo-tree").setup({
	-- 		event_handlers = {
	-- 			{
	-- 				event = "file_moved",
	-- 				handler = on_move,
	-- 			},
	-- 			{
	-- 				event = "file_renamed",
	-- 				handler = on_move,
	-- 			},
	-- 		},
	-- 		close_if_last_window = true,
	-- 		window = {
	-- 			position = "current",
	-- 		},
	-- 	})
	--
	-- 	vim.cmd([[hi NvimTreeNormal guibg=NONE ctermbg=NONE]])
	-- end,
}
